# Generated by Django 4.1.7 on 2023-04-04 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owners',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='owners',
            name='is_mvp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='owners',
            name='photo',
            field=models.ImageField(default='default_photo.jpg', upload_to='photos/%Y/%m/%d'),
        ),
    ]
