# Generated by Django 4.1.7 on 2023-04-02 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('clients_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user_id', models.IntegerField(blank=True)),
                ('property', models.CharField(max_length=200)),
            ],
        ),
    ]
